# Image for gitpod workspace
image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: ./gradlew quarkusDev

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-browser

# VSCode extensions
vscode:
  extensions:
    - "redhat.java"
    - "vscjava.vscode-java-dependency"
    - "vscjava.vscode-java-debug"
    - "vscjava.vscode-java-pack"